######################################################################
# Automatically generated by qmake (2.01a) jue nov 4 04:35:02 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Board.h mainwindow.h \
	AEstrella.h \
	NodoAEstrella.h \
	SetAEstrella.h \
	HeapAEstrella.h
FORMS += mainwindow.ui \

SOURCES += Board.cpp main.cpp mainwindow.cpp
