######################################################################
# Automatically generated by qmake (2.01a) vie nov 5 22:22:04 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += AStar.h AStarPathfinder.h Board.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += AStarPathfinder.cpp Board.cpp main.cpp mainwindow.cpp
